# Generated by Django 5.2.1 on 2025-05-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('장소/경험', '장소/경험'), ('일정/할일', '일정/할일'), ('단어', '단어'), ('콘텐츠', '콘텐츠'), ('꿈', '꿈'), ('기타', '기타')], max_length=20, verbose_name='기억 카테고리')),
                ('subcategory', models.CharField(blank=True, choices=[('', '없음'), ('영화', '영화'), ('노래', '노래'), ('드라마', '드라마'), ('애니메이션', '애니메이션'), ('학교', '학교'), ('회사', '회사'), ('알바', '알바'), ('기타', '기타')], max_length=20, verbose_name='세부 분류')),
                ('order', models.IntegerField(verbose_name='질문 순서 (Q2~Q15)')),
                ('text', models.TextField(verbose_name='질문 내용')),
            ],
        ),
    ]
