# Generated by Django 5.2.1 on 2025-06-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('장소', '장소'), ('일정/할일', '일정/할일'), ('단어/문장', '단어/문장'), ('콘텐츠', '콘텐츠'), ('노래', '노래'), ('검색', '검색')], max_length=20, verbose_name='기억 카테고리'),
        ),
    ]
