# Generated by Django 5.2.1 on 2025-06-03 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('장소/경험', '장소/경험'), ('일정/할일', '일정/할일'), ('단어', '단어'), ('콘텐츠', '콘텐츠'), ('꿈', '꿈'), ('기타', '기타')], max_length=20, verbose_name='기억 카테고리'),
        ),
    ]
