# Generated by Django 5.2.1 on 2025-06-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_memoryrecord_alter_question_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryrecord',
            old_name='user_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='memoryrecord',
            old_name='answer',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='memoryrecord',
            name='question',
        ),
        migrations.AddField(
            model_name='memoryrecord',
            name='keyword',
            field=models.CharField(default='어느 사용자의 기억', max_length=50),
        ),
        migrations.AddField(
            model_name='memoryrecord',
            name='qa_json',
            field=models.JSONField(default=list),
        ),
    ]
