# Generated by Django 5.2.2 on 2025-06-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_user_id_memoryrecord_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_clicks', models.IntegerField(default=0)),
                ('dont_save_clicks', models.IntegerField(default=0)),
                ('memory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='click_count', to='polls.memoryrecord')),
            ],
        ),
    ]
