# Generated by Django 5.2.2 on 2025-06-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_clickcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontSaveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clickcount',
            name='memory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='polls.memoryrecord'),
        ),
    ]
