# Generated by Django 5.2.1 on 2025-06-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_dontsavelog_alter_clickcount_memory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DontSaveLog',
        ),
    ]
