# Generated by Django 5.2.2 on 2025-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_dontsavelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalClickCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_clicks', models.IntegerField(default=0)),
                ('dont_save_clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ClickCount',
        ),
    ]
