# Generated by Django 5.2.2 on 2025-06-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_gameresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameResult',
        ),
    ]
